In [179]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [186]:
b = np.zeros((3, 2))
b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [188]:
b[:, 0] = a[1]
b

array([[4., 0.],
       [5., 0.],
       [6., 0.]])

In [192]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [200]:
b = a.reshape((-1, 5))
mask = b > 4

In [202]:
b = np.random.randint(0, 15, (5, 5))

In [203]:
b

array([[ 1, 10,  7,  6, 14],
       [14, 11,  4, 11,  6],
       [ 7, 10,  6,  0, 14],
       [ 0, 11, 12,  6,  2],
       [ 3, 12, 11, 14,  9]])

In [208]:
mask = b > 6
mask

array([[False,  True,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True, False, False,  True],
       [False,  True,  True, False, False],
       [False,  True,  True,  True,  True]])

In [217]:
mask[np.arange(5), 0] = np.sum(mask.astype(np.int), axis=1) * 1

In [222]:
np.ones_like()

array([1, 1])

In [212]:
np.sum(b * mask, axis=1) - 1

array([30, 35, 30, 22, 45])

In [197]:

b[[1, 2, 3, 4], [1, 2, 3, 4]].reshape((-1, 1))

array([[ 6],
       [12],
       [18],
       [24]])